declare module 'react-pivottable/TableRenderers'
declare module 'react-pivottable/PivotTable'
declare module 'react-pivottable/PivotTableUI'
declare module 'react-pivottable/Utilities'
declare module 'react-plotly.js/factory'
declare module 'react-pivottable/PlotlyRenderers'